window.docContents[63].resolve({"/#PSBP-Documentation--Programming-With-Failure--ProgramWithFailure":{"id":"/#PSBP-Documentation--Programming-With-Failure--ProgramWithFailure","header":"10.3. ProgramWithFailure","context":"PSBP Documentation\u0009Programming With Failure","contents":"abbrev ProgramWithFailure ε computation :=\n  FromComputationValuedFunction (FailureT ε computation)\n\ndef materializeWithFailure\n    [Monad computation] {α β : Type} :\n  ProgramWithFailure ε computation α β →\n  α →\n  computation (ε ⊕ β) :=\n    λ ⟨αftεcβ⟩ α =>\n      (αftεcβ α).toComputationOfSum\n\ndef materializeActiveWithFailure {α β : Type} :\n ProgramWithFailure ε Active α β → α → (ε ⊕ β) :=\n  materializeWithFailure\n\n\ninstance Monad (FailureT ε computation) and materializeActiveWithFailure above cause programs to a fail fast when a\nfirst exception has been encountered. The examples below illustrate this.\n\n"}});